### ISSUE TITLE
Mummerplot diagonalize panels in facet grid 

### ISSUE THREAD

**Issue by hrpelg** [jmonlong/Hippocamplus#2]
[Rplots.pdf](https://github.com/jmonlong/Hippocamplus/files/2523517/Rplots.pdf)
 Hi Jean, 
That is the plot I get and it would be so cool to make a diagonal of the matching panels between chr1 of assembly and chr1 of reference and so on.

Thanks a lot 

E

**Comment by jmonlong** [comment]
Ok, I updated the post, I think it should work now with the new *diagMum* function. I haven't tested it though because I don't have the appropriate data. If it doesn't work you could always send me your data.

Now it should follow whatever order the *rid* are in. I also changed the *filterMum* function to not give *rid* any special order. By default it should be the alphabetical order or you can always define your favorite order with factors first. 

Side note, you might want to hide the numbers in the x axis too by adding `axis.text.x=element_blank()` in the *theme* function of the ggplot2 line.

Let me know how it goes

**Comment by jmonlong** [comment]
For posterity, here is the final ggplot command with some small aesthetic changes: 

```r
ggplot(mumgp.filt.diag, aes(x=rs, xend=re, y=qs, yend=qe, colour=strand)) +
  geom_segment(show.legend=FALSE) + geom_point(alpha=0.09) + theme_bw() + 
  facet_grid(qid~rid, scales='free', space='free', switch='both') +
  guides(colour=guide_legend(override.aes=list(alpha=1))) + 
  theme(strip.text.y=element_text(angle=180, size=10),
        strip.text.x=element_text(size=10),
        strip.background=element_blank(),
        legend.position=c(1,-.03), legend.justification=c(1,1),
        legend.direction='horizontal',
        axis.text.y=element_blank(), axis.ticks.y=element_blank(),
        axis.text.x=element_blank(), axis.ticks.x=element_blank(),
        panel.spacing=unit(0, 'cm')) +
  xlab('reference sequence') + ylab('assembly') + scale_colour_brewer(palette='Set1')
```

Producing: 

![mummerggplot](https://user-images.githubusercontent.com/5704457/47767406-ba12dd80-dc90-11e8-90a6-df367c2b2b5f.png)

**Comment by touala** [comment]
Neat plot, thanks for sharing.
